
package com.bjjw.dmsmaintenanceservice.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAccessBusWCF", targetNamespace = "http:/DST_V2/AccessBus")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAccessBusWCF {


    /**
     * 
     * @param windDataStr
     * @param nodeId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "A_HandleWindData", action = "http:/DST_V2/AccessBus/IAccessBusWCF/A_HandleWindData")
    @WebResult(name = "A_HandleWindDataResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "A_HandleWindData", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.AHandleWindData")
    @ResponseWrapper(localName = "A_HandleWindDataResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.AHandleWindDataResponse")
    public Boolean aHandleWindData(
            @WebParam(name = "nodeId", targetNamespace = "http:/DST_V2/AccessBus")
                    String nodeId,
            @WebParam(name = "windDataStr", targetNamespace = "http:/DST_V2/AccessBus")
                    String windDataStr);

    /**
     * 
     * @param nodeId
     * @param rainDataStr
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "A_HandleRainData", action = "http:/DST_V2/AccessBus/IAccessBusWCF/A_HandleRainData")
    @WebResult(name = "A_HandleRainDataResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "A_HandleRainData", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.AHandleRainData")
    @ResponseWrapper(localName = "A_HandleRainDataResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.AHandleRainDataResponse")
    public Boolean aHandleRainData(
            @WebParam(name = "nodeId", targetNamespace = "http:/DST_V2/AccessBus")
                    String nodeId,
            @WebParam(name = "rainDataStr", targetNamespace = "http:/DST_V2/AccessBus")
                    String rainDataStr);

    /**
     * 
     * @param snowDataStr
     * @param nodeId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "A_HandlSnowData", action = "http:/DST_V2/AccessBus/IAccessBusWCF/A_HandlSnowData")
    @WebResult(name = "A_HandlSnowDataResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "A_HandlSnowData", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.AHandlSnowData")
    @ResponseWrapper(localName = "A_HandlSnowDataResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.AHandlSnowDataResponse")
    public Boolean aHandlSnowData(
            @WebParam(name = "nodeId", targetNamespace = "http:/DST_V2/AccessBus")
                    String nodeId,
            @WebParam(name = "snowDataStr", targetNamespace = "http:/DST_V2/AccessBus")
                    String snowDataStr);

    /**
     * 
     * @param environmentDataStr
     * @param nodeId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "A_HandlEnvironmentData", action = "http:/DST_V2/AccessBus/IAccessBusWCF/A_HandlEnvironmentData")
    @WebResult(name = "A_HandlEnvironmentDataResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "A_HandlEnvironmentData", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.AHandlEnvironmentData")
    @ResponseWrapper(localName = "A_HandlEnvironmentDataResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.AHandlEnvironmentDataResponse")
    public Boolean aHandlEnvironmentData(
            @WebParam(name = "nodeId", targetNamespace = "http:/DST_V2/AccessBus")
                    String nodeId,
            @WebParam(name = "environmentDataStr", targetNamespace = "http:/DST_V2/AccessBus")
                    String environmentDataStr);

    /**
     * 
     * @param nodeId
     * @param foreignMatterAlarmStr
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "B_HandleForeignMatterAlarm", action = "http:/DST_V2/AccessBus/IAccessBusWCF/B_HandleForeignMatterAlarm")
    @WebResult(name = "B_HandleForeignMatterAlarmResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "B_HandleForeignMatterAlarm", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.BHandleForeignMatterAlarm")
    @ResponseWrapper(localName = "B_HandleForeignMatterAlarmResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.BHandleForeignMatterAlarmResponse")
    public Boolean bHandleForeignMatterAlarm(
            @WebParam(name = "nodeId", targetNamespace = "http:/DST_V2/AccessBus")
                    String nodeId,
            @WebParam(name = "foreignMatterAlarmStr", targetNamespace = "http:/DST_V2/AccessBus")
                    String foreignMatterAlarmStr);

    /**
     * 
     * @param nodeId
     * @param earthQuakeAlarmStr
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "B_HandleEarthQuakeAlarm", action = "http:/DST_V2/AccessBus/IAccessBusWCF/B_HandleEarthQuakeAlarm")
    @WebResult(name = "B_HandleEarthQuakeAlarmResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "B_HandleEarthQuakeAlarm", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.BHandleEarthQuakeAlarm")
    @ResponseWrapper(localName = "B_HandleEarthQuakeAlarmResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.BHandleEarthQuakeAlarmResponse")
    public Boolean bHandleEarthQuakeAlarm(
            @WebParam(name = "nodeId", targetNamespace = "http:/DST_V2/AccessBus")
                    String nodeId,
            @WebParam(name = "earthQuakeAlarmStr", targetNamespace = "http:/DST_V2/AccessBus")
                    String earthQuakeAlarmStr);

    /**
     * 
     * @param cmdEntiy
     * @param nodeId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "C_RemoteCMDControl", action = "http:/DST_V2/AccessBus/IAccessBusWCF/C_RemoteCMDControl")
    @WebResult(name = "C_RemoteCMDControlResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "C_RemoteCMDControl", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.CRemoteCMDControl")
    @ResponseWrapper(localName = "C_RemoteCMDControlResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.CRemoteCMDControlResponse")
    public Boolean cRemoteCMDControl(
            @WebParam(name = "nodeId", targetNamespace = "http:/DST_V2/AccessBus")
                    String nodeId,
            @WebParam(name = "cmdEntiy", targetNamespace = "http:/DST_V2/AccessBus")
                    CMDEntity cmdEntiy);

    /**
     * 
     * @param cmdStr
     * @param nodeId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "C_CMDControl", action = "http:/DST_V2/AccessBus/IAccessBusWCF/C_CMDControl")
    @WebResult(name = "C_CMDControlResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "C_CMDControl", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.CCMDControl")
    @ResponseWrapper(localName = "C_CMDControlResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.CCMDControlResponse")
    public Boolean cCMDControl(
            @WebParam(name = "nodeId", targetNamespace = "http:/DST_V2/AccessBus")
                    String nodeId,
            @WebParam(name = "cmdStr", targetNamespace = "http:/DST_V2/AccessBus")
                    String cmdStr);

    /**
     * 
     * @param windSensorStatusStr
     * @param nodeId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "D_HandleWindSensorStatus", action = "http:/DST_V2/AccessBus/IAccessBusWCF/D_HandleWindSensorStatus")
    @WebResult(name = "D_HandleWindSensorStatusResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "D_HandleWindSensorStatus", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.DHandleWindSensorStatus")
    @ResponseWrapper(localName = "D_HandleWindSensorStatusResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.DHandleWindSensorStatusResponse")
    public Boolean dHandleWindSensorStatus(
            @WebParam(name = "nodeId", targetNamespace = "http:/DST_V2/AccessBus")
                    String nodeId,
            @WebParam(name = "windSensorStatusStr", targetNamespace = "http:/DST_V2/AccessBus")
                    String windSensorStatusStr);

    /**
     * 
     * @param rainSensorStatusStr
     * @param nodeId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "D_HandleRainSensorStatus", action = "http:/DST_V2/AccessBus/IAccessBusWCF/D_HandleRainSensorStatus")
    @WebResult(name = "D_HandleRainSensorStatusResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "D_HandleRainSensorStatus", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.DHandleRainSensorStatus")
    @ResponseWrapper(localName = "D_HandleRainSensorStatusResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.DHandleRainSensorStatusResponse")
    public Boolean dHandleRainSensorStatus(
            @WebParam(name = "nodeId", targetNamespace = "http:/DST_V2/AccessBus")
                    String nodeId,
            @WebParam(name = "rainSensorStatusStr", targetNamespace = "http:/DST_V2/AccessBus")
                    String rainSensorStatusStr);

    /**
     * 
     * @param snowSensorStatusStr
     * @param nodeId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "D_HandleSnowSensorStatus", action = "http:/DST_V2/AccessBus/IAccessBusWCF/D_HandleSnowSensorStatus")
    @WebResult(name = "D_HandleSnowSensorStatusResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "D_HandleSnowSensorStatus", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.DHandleSnowSensorStatus")
    @ResponseWrapper(localName = "D_HandleSnowSensorStatusResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.DHandleSnowSensorStatusResponse")
    public Boolean dHandleSnowSensorStatus(
            @WebParam(name = "nodeId", targetNamespace = "http:/DST_V2/AccessBus")
                    String nodeId,
            @WebParam(name = "snowSensorStatusStr", targetNamespace = "http:/DST_V2/AccessBus")
                    String snowSensorStatusStr);

    /**
     * 
     * @param foreignMatterRelayStatusStr
     * @param nodeId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "D_HandleForeignMatterRelayStatus", action = "http:/DST_V2/AccessBus/IAccessBusWCF/D_HandleForeignMatterRelayStatus")
    @WebResult(name = "D_HandleForeignMatterRelayStatusResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "D_HandleForeignMatterRelayStatus", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.DHandleForeignMatterRelayStatus")
    @ResponseWrapper(localName = "D_HandleForeignMatterRelayStatusResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.DHandleForeignMatterRelayStatusResponse")
    public Boolean dHandleForeignMatterRelayStatus(
            @WebParam(name = "nodeId", targetNamespace = "http:/DST_V2/AccessBus")
                    String nodeId,
            @WebParam(name = "foreignMatterRelayStatusStr", targetNamespace = "http:/DST_V2/AccessBus")
                    String foreignMatterRelayStatusStr);

    /**
     * 
     * @param earthQuakeRelayStatusStr
     * @param nodeId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "D_HandleEarthQuakeRelayStatus", action = "http:/DST_V2/AccessBus/IAccessBusWCF/D_HandleEarthQuakeRelayStatus")
    @WebResult(name = "D_HandleEarthQuakeRelayStatusResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "D_HandleEarthQuakeRelayStatus", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.DHandleEarthQuakeRelayStatus")
    @ResponseWrapper(localName = "D_HandleEarthQuakeRelayStatusResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.DHandleEarthQuakeRelayStatusResponse")
    public Boolean dHandleEarthQuakeRelayStatus(
            @WebParam(name = "nodeId", targetNamespace = "http:/DST_V2/AccessBus")
                    String nodeId,
            @WebParam(name = "earthQuakeRelayStatusStr", targetNamespace = "http:/DST_V2/AccessBus")
                    String earthQuakeRelayStatusStr);

    /**
     * 
     * @param nodeId
     * @param earthQuakeSensorStatusStr
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "D_HandleEarthQuakeSensorStatus", action = "http:/DST_V2/AccessBus/IAccessBusWCF/D_HandleEarthQuakeSensorStatus")
    @WebResult(name = "D_HandleEarthQuakeSensorStatusResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "D_HandleEarthQuakeSensorStatus", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.DHandleEarthQuakeSensorStatus")
    @ResponseWrapper(localName = "D_HandleEarthQuakeSensorStatusResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.DHandleEarthQuakeSensorStatusResponse")
    public Boolean dHandleEarthQuakeSensorStatus(
            @WebParam(name = "nodeId", targetNamespace = "http:/DST_V2/AccessBus")
                    String nodeId,
            @WebParam(name = "earthQuakeSensorStatusStr", targetNamespace = "http:/DST_V2/AccessBus")
                    String earthQuakeSensorStatusStr);

    /**
     * 
     * @param monitorUnitDeviceStatusStr
     * @param nodeId
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "D_HandleMonitorUnitDeviceStatus", action = "http:/DST_V2/AccessBus/IAccessBusWCF/D_HandleMonitorUnitDeviceStatus")
    @WebResult(name = "D_HandleMonitorUnitDeviceStatusResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "D_HandleMonitorUnitDeviceStatus", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.DHandleMonitorUnitDeviceStatus")
    @ResponseWrapper(localName = "D_HandleMonitorUnitDeviceStatusResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.DHandleMonitorUnitDeviceStatusResponse")
    public Boolean dHandleMonitorUnitDeviceStatus(
            @WebParam(name = "nodeId", targetNamespace = "http:/DST_V2/AccessBus")
                    String nodeId,
            @WebParam(name = "monitorUnitDeviceStatusStr", targetNamespace = "http:/DST_V2/AccessBus")
                    String monitorUnitDeviceStatusStr);

    /**
     * 
     * @param lineCode
     * @param bureauCode
     * @param clientId
     * @param monitorPointCode
     * @param interfaceGateId
     * @param monitorUnitCode
     * @param snowDepthImageStr
     */
    @WebMethod(operationName = "E_UpLoadSnowDepthImage", action = "http:/DST_V2/AccessBus/IAccessBusWCF/E_UpLoadSnowDepthImage")
    @RequestWrapper(localName = "E_UpLoadSnowDepthImage", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.EUpLoadSnowDepthImage")
    @ResponseWrapper(localName = "E_UpLoadSnowDepthImageResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.EUpLoadSnowDepthImageResponse")
    public void eUpLoadSnowDepthImage(
            @WebParam(name = "interfaceGateId", targetNamespace = "http:/DST_V2/AccessBus")
                    String interfaceGateId,
            @WebParam(name = "clientId", targetNamespace = "http:/DST_V2/AccessBus")
                    String clientId,
            @WebParam(name = "bureauCode", targetNamespace = "http:/DST_V2/AccessBus")
                    String bureauCode,
            @WebParam(name = "lineCode", targetNamespace = "http:/DST_V2/AccessBus")
                    String lineCode,
            @WebParam(name = "monitorUnitCode", targetNamespace = "http:/DST_V2/AccessBus")
                    String monitorUnitCode,
            @WebParam(name = "monitorPointCode", targetNamespace = "http:/DST_V2/AccessBus")
                    String monitorPointCode,
            @WebParam(name = "snowDepthImageStr", targetNamespace = "http:/DST_V2/AccessBus")
                    String snowDepthImageStr);

    /**
     * 
     * @param dataEntity
     * @param statusEntity
     * @param monitorUnitEntity
     */
    @WebMethod(operationName = "F_HandleForeignMonitorData", action = "http:/DST_V2/AccessBus/IAccessBusWCF/F_HandleForeignMonitorData")
    @RequestWrapper(localName = "F_HandleForeignMonitorData", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.FHandleForeignMonitorData")
    @ResponseWrapper(localName = "F_HandleForeignMonitorDataResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.FHandleForeignMonitorDataResponse")
    public void fHandleForeignMonitorData(
            @WebParam(name = "dataEntity", targetNamespace = "http:/DST_V2/AccessBus")
                    DataEntity dataEntity,
            @WebParam(name = "statusEntity", targetNamespace = "http:/DST_V2/AccessBus")
                    StatusEntity statusEntity,
            @WebParam(name = "monitorUnitEntity", targetNamespace = "http:/DST_V2/AccessBus")
                    MonitorUnitDeviceStatusEntity monitorUnitEntity);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "G_GetBureaCode", action = "http:/DST_V2/AccessBus/IAccessBusWCF/G_GetBureaCode")
    @WebResult(name = "G_GetBureaCodeResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "G_GetBureaCode", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.GGetBureaCode")
    @ResponseWrapper(localName = "G_GetBureaCodeResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.GGetBureaCodeResponse")
    public String gGetBureaCode();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "G_GetLineCode", action = "http:/DST_V2/AccessBus/IAccessBusWCF/G_GetLineCode")
    @WebResult(name = "G_GetLineCodeResult", targetNamespace = "http:/DST_V2/AccessBus")
    @RequestWrapper(localName = "G_GetLineCode", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.GGetLineCode")
    @ResponseWrapper(localName = "G_GetLineCodeResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.GGetLineCodeResponse")
    public String gGetLineCode();

    /**
     * 
     * @param rainDataStr
     */
    @WebMethod(operationName = "G_SendSpecifiedRainData", action = "http:/DST_V2/AccessBus/IAccessBusWCF/G_SendSpecifiedRainData")
    @RequestWrapper(localName = "G_SendSpecifiedRainData", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.GSendSpecifiedRainData")
    @ResponseWrapper(localName = "G_SendSpecifiedRainDataResponse", targetNamespace = "http:/DST_V2/AccessBus", className = "JavaSrc.GSendSpecifiedRainDataResponse")
    public void gSendSpecifiedRainData(
            @WebParam(name = "rainDataStr", targetNamespace = "http:/DST_V2/AccessBus")
                    String rainDataStr);

}
